// RuView SkyGraph dashboard (ADR-199 presentation plane, "dashboard first").
//
// Renders the embedded deterministic scenario (sky-demo-data.js, generated by
// `cargo run -p sky-monitor --release -- --emit-json ui/dashboard/sky-demo-data.js`)
// on an all-sky polar plot with replay, trails, and anomaly badges.
//
// Projection math: the JS functions below mirror coords.rs (WGS-84 geodetic ->
// ECEF -> ENU -> az/el/range) so the page works standalone. When the wasm-pack
// output is present at ./pkg/sky_monitor_wasm.js (see README.md) it is loaded
// automatically and its SkyProjector.project_batch replaces the JS math.

/* global SKY_DATA */

// ---------------------------------------------------------------------------
// Projection (JS mirror of examples/sky-monitor/src/coords.rs — replaced by
// the wasm module when built).
// ---------------------------------------------------------------------------

const WGS84_A = 6378137.0;
const WGS84_F = 1.0 / 298.257223563;
const WGS84_E2 = WGS84_F * (2.0 - WGS84_F);
const DEG = Math.PI / 180.0;

function geodeticToEcef(latDeg, lonDeg, altM) {
  const lat = latDeg * DEG, lon = lonDeg * DEG;
  const sLat = Math.sin(lat), cLat = Math.cos(lat);
  const sLon = Math.sin(lon), cLon = Math.cos(lon);
  const n = WGS84_A / Math.sqrt(1.0 - WGS84_E2 * sLat * sLat); // prime vertical
  return [
    (n + altM) * cLat * cLon,
    (n + altM) * cLat * sLon,
    (n * (1.0 - WGS84_E2) + altM) * sLat,
  ];
}

function normalizeDeg(d) {
  const r = d % 360.0;
  return r < 0.0 ? r + 360.0 : r;
}

// Full WGS-84 -> observer az/el/range/bearing projection (coords.rs
// observer_frame). Returns [azDeg, elDeg, rangeM, bearingDeg].
function observerFrameJs(obs, obsEcef, lat, lon, altM) {
  const t = geodeticToEcef(lat, lon, altM);
  const dx = t[0] - obsEcef[0], dy = t[1] - obsEcef[1], dz = t[2] - obsEcef[2];
  const la = obs.lat * DEG, lo = obs.lon * DEG;
  const sLat = Math.sin(la), cLat = Math.cos(la);
  const sLon = Math.sin(lo), cLon = Math.cos(lo);
  const e = -sLon * dx + cLon * dy;
  const n = -sLat * cLon * dx - sLat * sLon * dy + cLat * dz;
  const u = cLat * cLon * dx + cLat * sLon * dy + sLat * dz;
  const horizontal = Math.hypot(e, n);
  const range = Math.hypot(horizontal, u);
  const az = horizontal < 1e-9 ? 0.0 : normalizeDeg(Math.atan2(e, n) / DEG);
  const el = Math.atan2(u, horizontal) / DEG;
  // Great-circle initial bearing observer -> target.
  const phi2 = lat * DEG, dl = (lon - obs.lon) * DEG;
  const by = Math.sin(dl) * Math.cos(phi2);
  const bx = Math.cos(la) * Math.sin(phi2) - Math.sin(la) * Math.cos(phi2) * Math.cos(dl);
  const bearing = normalizeDeg(Math.atan2(by, bx) / DEG);
  return [az, el, range, bearing];
}

// Polar "fisheye" all-sky mapping (mirror of wasm/src/screen.rs): zenith at
// the centre, horizon on the inscribed circle, azimuth 0 = North = up.
function polarScreenXY(azDeg, elDeg, width, height) {
  const cx = width / 2, cy = height / 2;
  const radius = Math.min(width, height) / 2;
  const el = Math.max(-90, Math.min(90, elDeg));
  const r = ((90 - el) / 90) * radius;
  const az = azDeg * DEG;
  return [cx + r * Math.sin(az), cy - r * Math.cos(az), elDeg >= 0];
}

// ---------------------------------------------------------------------------
// Optional wasm engine (preferred when ./pkg exists).
// ---------------------------------------------------------------------------

async function loadWasmProjector(obs) {
  try {
    const mod = await import("./pkg/sky_monitor_wasm.js");
    await mod.default(); // init wasm
    const projector = new mod.SkyProjector(obs.lat, obs.lon, obs.alt_m);
    return { projectBatch: (flat) => projector.project_batch(flat), version: mod.version() };
  } catch (_e) {
    return null; // pkg not built — JS fallback stays active
  }
}

// ---------------------------------------------------------------------------
// Scene preparation: project every track point once, cache az/el/range.
// ---------------------------------------------------------------------------

const BAND_COLORS = {
  "normal": "#3ddc84",
  "mildly unusual": "#e8d44d",
  "interesting": "#ff9f43",
  "strong anomaly": "#ff5252",
  "rare": "#d05aff",
  "baseline": "#5a6378",
};
const TRAIL_SECS = 150;   // trail length behind the dot
const LINGER_SECS = 20;   // dot stays this long after the last sample
const PLAY_SPEED = 60;    // replay seconds per wall-clock second

function projectAll(tracks, projectBatch, obs, obsEcef) {
  for (const tr of tracks) {
    if (projectBatch) {
      const flat = new Float64Array(tr.points.length * 3);
      tr.points.forEach((p, i) => { flat[i * 3] = p.lat; flat[i * 3 + 1] = p.lon; flat[i * 3 + 2] = p.alt_m; });
      const out = projectBatch(flat); // [az, el, range, bearing] * N
      tr.points.forEach((p, i) => { p.az = out[i * 4]; p.el = out[i * 4 + 1]; p.range = out[i * 4 + 2]; });
    } else {
      for (const p of tr.points) {
        const [az, el, range] = observerFrameJs(obs, obsEcef, p.lat, p.lon, p.alt_m);
        p.az = az; p.el = el; p.range = range;
      }
    }
    tr.t0 = tr.points[0].t;
    tr.t1 = tr.points[tr.points.length - 1].t;
    tr.band = tr.anomaly ? tr.anomaly.band : "baseline";
    tr.color = BAND_COLORS[tr.band] || BAND_COLORS.baseline;
    tr.label = tr.callsign || tr.icao24;
  }
}

// Last point index with p.t <= t (binary search; points are 1 Hz ordered).
function indexAt(tr, t) {
  if (t < tr.t0) return -1;
  let lo = 0, hi = tr.points.length - 1;
  while (lo < hi) {
    const mid = (lo + hi + 1) >> 1;
    if (tr.points[mid].t <= t) lo = mid; else hi = mid - 1;
  }
  return lo;
}

// ---------------------------------------------------------------------------
// Rendering.
// ---------------------------------------------------------------------------

function drawSkyDome(ctx, w, h) {
  const cx = w / 2, cy = h / 2;
  const R = Math.min(w, h) / 2;
  // Elevation rings at 0 / 30 / 60 degrees.
  for (const el of [0, 30, 60]) {
    const r = ((90 - el) / 90) * R;
    ctx.beginPath();
    ctx.arc(cx, cy, r, 0, Math.PI * 2);
    ctx.strokeStyle = el === 0 ? "#27345c" : "#1a2542";
    ctx.lineWidth = el === 0 ? 1.5 : 1;
    ctx.stroke();
    ctx.fillStyle = "#3d4d78";
    ctx.font = "10px monospace";
    ctx.fillText(`${el}°`, cx + 4, cy - r + 12);
  }
  // Cross hairs + compass labels (N up, E right, S down, W left).
  ctx.strokeStyle = "#16203c";
  ctx.beginPath();
  ctx.moveTo(cx - R, cy); ctx.lineTo(cx + R, cy);
  ctx.moveTo(cx, cy - R); ctx.lineTo(cx, cy + R);
  ctx.stroke();
  ctx.fillStyle = "#7e90bd";
  ctx.font = "bold 13px monospace";
  ctx.textAlign = "center";
  ctx.fillText("N", cx, cy - R + 16);
  ctx.fillText("S", cx, cy + R - 8);
  ctx.fillText("E", cx + R - 10, cy + 4);
  ctx.fillText("W", cx - R + 10, cy + 4);
  ctx.textAlign = "left";
}

function drawTrack(ctx, tr, t, w, h, selected) {
  const i = indexAt(tr, t);
  if (i < 0 || t > tr.t1 + LINGER_SECS) return false;
  // Fading trail.
  ctx.lineWidth = 1.5;
  for (let j = Math.max(1, i - TRAIL_SECS); j <= i; j++) {
    const a = tr.points[j - 1], b = tr.points[j];
    const [x1, y1] = polarScreenXY(a.az, a.el, w, h);
    const [x2, y2, vis] = polarScreenXY(b.az, b.el, w, h);
    if (!vis && b.el < -2) continue;
    const age = (i - j) / TRAIL_SECS;
    ctx.strokeStyle = tr.color;
    ctx.globalAlpha = 0.55 * (1 - age);
    ctx.beginPath(); ctx.moveTo(x1, y1); ctx.lineTo(x2, y2); ctx.stroke();
  }
  ctx.globalAlpha = 1;
  // Current dot.
  const p = tr.points[i];
  const [x, y, visible] = polarScreenXY(p.az, p.el, w, h);
  if (!visible) return false;
  const gone = t > tr.t1; // lingering after last sample
  ctx.globalAlpha = gone ? Math.max(0, 1 - (t - tr.t1) / LINGER_SECS) : 1;
  ctx.fillStyle = tr.color;
  ctx.beginPath(); ctx.arc(x, y, selected ? 5 : 3.5, 0, Math.PI * 2); ctx.fill();
  // Overhead-candidate highlight ring.
  if (tr.overhead) {
    ctx.strokeStyle = "#5aa9ff";
    ctx.lineWidth = 1.2;
    ctx.beginPath(); ctx.arc(x, y, 9, 0, Math.PI * 2); ctx.stroke();
  }
  if (selected) {
    ctx.strokeStyle = tr.color;
    ctx.lineWidth = 1;
    ctx.beginPath(); ctx.arc(x, y, 13, 0, Math.PI * 2); ctx.stroke();
  }
  // Callsign + altitude label.
  ctx.fillStyle = "#c7d2e8";
  ctx.font = "11px monospace";
  ctx.fillText(`${tr.label} ${Math.round(p.alt_m)}m`, x + 12, y - 6);
  ctx.globalAlpha = 1;
  return true;
}

// ---------------------------------------------------------------------------
// App.
// ---------------------------------------------------------------------------

async function main() {
  const obs = SKY_DATA.observer;
  const tracks = SKY_DATA.tracks;
  const canvas = document.getElementById("sky");
  const ctx = canvas.getContext("2d");
  const scrubber = document.getElementById("scrubber");
  const clock = document.getElementById("clock");
  const playBtn = document.getElementById("play");
  const engineLabel = document.getElementById("engine");
  document.getElementById("observer-label").textContent =
    `observer: ${obs.name} (${obs.lat.toFixed(4)}, ${obs.lon.toFixed(4)}, ${obs.alt_m} m)`;

  // Prefer wasm projection when ./pkg is present; otherwise mirror in JS.
  const wasm = await loadWasmProjector(obs);
  engineLabel.textContent = wasm
    ? `projection: wasm (sky-monitor-wasm ${wasm.version})`
    : "projection: JS fallback (build ./pkg for wasm)";
  projectAll(tracks, wasm && wasm.projectBatch, obs, geodeticToEcef(obs.lat, obs.lon, obs.alt_m));

  const tMin = Math.min(...tracks.map((tr) => tr.t0));
  const tMax = Math.max(...tracks.map((tr) => tr.t1)) + LINGER_SECS;
  let t = tMin;
  let playing = false;
  let selected = null;
  let lastFrame = performance.now();

  // --- Side panel -----------------------------------------------------------
  const tbody = document.querySelector("#track-table tbody");
  const reasons = document.getElementById("reasons");
  const rows = new Map();
  for (const tr of tracks) {
    const row = document.createElement("tr");
    row.className = "track-row";
    const score = tr.anomaly ? tr.anomaly.score.toFixed(3) : "—";
    const last = tr.points[tr.points.length - 1];
    row.innerHTML =
      `<td>${tr.label}${tr.overhead ? " ◎" : ""}</td>` +
      `<td>${Math.round(last.alt_m)}</td>` +
      `<td>${headingOf(tr)}°</td>` +
      `<td><span class="badge" style="background:${tr.color}">${tr.band}</span></td>` +
      `<td>${score}</td>`;
    row.addEventListener("click", () => {
      selected = selected === tr ? null : tr;
      if (selected) t = Math.max(tMin, tr.t0); // jump replay to the track
      showReasons();
      syncScrubber();
      render();
    });
    tbody.appendChild(row);
    rows.set(tr, row);
  }

  function headingOf(tr) {
    // Circular mean over the projected ground path (display only).
    let s = 0, c = 0;
    for (let i = 1; i < tr.points.length; i += 10) {
      const a = tr.points[i - 1], b = tr.points[i];
      const brg = Math.atan2(b.lon - a.lon, b.lat - a.lat);
      s += Math.sin(brg); c += Math.cos(brg);
    }
    return Math.round(normalizeDeg(Math.atan2(s, c) / DEG));
  }

  function showReasons() {
    if (!selected) {
      reasons.innerHTML = '<div class="reason">Select a track below.</div>';
      return;
    }
    const who = `<div class="who">${selected.label} (icao24 ${selected.icao24})` +
      `${selected.overhead ? " — overhead candidate" : ""}</div>`;
    if (!selected.anomaly) {
      reasons.innerHTML = `${who}<div class="reason">baseline track — unscored (ADR §26: baseline before alerting)</div>`;
      return;
    }
    reasons.innerHTML = who + selected.anomaly.reasons
      .map((r) => `<div class="reason" style="border-color:${selected.color}">${r}</div>`)
      .join("");
  }

  // --- Replay / scrubber ----------------------------------------------------
  function syncScrubber() {
    scrubber.value = String(Math.round(((t - tMin) / (tMax - tMin)) * 1000));
  }
  scrubber.addEventListener("input", () => {
    t = tMin + (Number(scrubber.value) / 1000) * (tMax - tMin);
    render();
  });
  playBtn.addEventListener("click", () => {
    playing = !playing;
    playBtn.textContent = playing ? "Pause" : "Play";
    lastFrame = performance.now();
    if (playing) requestAnimationFrame(tick);
  });

  function tick(now) {
    if (!playing) return;
    t += ((now - lastFrame) / 1000) * PLAY_SPEED;
    lastFrame = now;
    if (t >= tMax) { t = tMin; } // loop the day
    syncScrubber();
    render();
    requestAnimationFrame(tick);
  }

  // --- Render ----------------------------------------------------------------
  function render() {
    const dpr = window.devicePixelRatio || 1;
    const w = canvas.clientWidth, h = canvas.clientHeight;
    if (canvas.width !== w * dpr || canvas.height !== h * dpr) {
      canvas.width = w * dpr; canvas.height = h * dpr;
    }
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    ctx.clearRect(0, 0, w, h);
    drawSkyDome(ctx, w, h);
    for (const tr of tracks) {
      const live = drawTrack(ctx, tr, t, w, h, tr === selected);
      rows.get(tr).classList.toggle("live", live);
      rows.get(tr).classList.toggle("active", tr === selected);
    }
    clock.textContent = new Date(t * 1000).toISOString().replace("T", " ").slice(0, 19) + " UTC";
  }

  window.addEventListener("resize", render);
  syncScrubber();
  render();
}

main();
